/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as CollectionsSoldoutRouteImport } from './routes/collections/soldout'
import { Route as CollectionsOldRouteImport } from './routes/collections/old'
import { Route as CollectionsNewRouteImport } from './routes/collections/new'
import { Route as CollectionsAccessoriesRouteImport } from './routes/collections/accessories'
import { Route as AccountUpdateInformationRouteImport } from './routes/account/update-information'
import { Route as AccountRegisterRouteImport } from './routes/account/register'

const PolicyTermsConditionsLazyRouteImport = createFileRoute(
  '/policy/terms-conditions',
)()
const PolicyShippingPolicyLazyRouteImport = createFileRoute(
  '/policy/shipping-policy',
)()
const PolicyRefundPolicyLazyRouteImport = createFileRoute(
  '/policy/refund-policy',
)()
const PolicyPrivacyPolicyLazyRouteImport = createFileRoute(
  '/policy/privacy-policy',
)()
const PaymentSuccessfulLazyRouteImport = createFileRoute(
  '/payment/successful',
)()
const InfoAboutLazyRouteImport = createFileRoute('/info/about')()
const InfoFAQLazyRouteImport = createFileRoute('/info/FAQ')()
const CollectionsAllLazyRouteImport = createFileRoute('/collections/all')()
const AccountUpdatePasswordLazyRouteImport = createFileRoute(
  '/account/update-password',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyTermsConditionsLazyRoute =
  PolicyTermsConditionsLazyRouteImport.update({
    id: '/policy/terms-conditions',
    path: '/policy/terms-conditions',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/policy/terms-conditions.lazy').then((d) => d.Route),
  )
const PolicyShippingPolicyLazyRoute =
  PolicyShippingPolicyLazyRouteImport.update({
    id: '/policy/shipping-policy',
    path: '/policy/shipping-policy',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/policy/shipping-policy.lazy').then((d) => d.Route),
  )
const PolicyRefundPolicyLazyRoute = PolicyRefundPolicyLazyRouteImport.update({
  id: '/policy/refund-policy',
  path: '/policy/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/policy/refund-policy.lazy').then((d) => d.Route),
)
const PolicyPrivacyPolicyLazyRoute = PolicyPrivacyPolicyLazyRouteImport.update({
  id: '/policy/privacy-policy',
  path: '/policy/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/policy/privacy-policy.lazy').then((d) => d.Route),
)
const PaymentSuccessfulLazyRoute = PaymentSuccessfulLazyRouteImport.update({
  id: '/payment/successful',
  path: '/payment/successful',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/payment/successful.lazy').then((d) => d.Route),
)
const InfoAboutLazyRoute = InfoAboutLazyRouteImport.update({
  id: '/info/about',
  path: '/info/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/info/about.lazy').then((d) => d.Route))
const InfoFAQLazyRoute = InfoFAQLazyRouteImport.update({
  id: '/info/FAQ',
  path: '/info/FAQ',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/info/FAQ.lazy').then((d) => d.Route))
const CollectionsAllLazyRoute = CollectionsAllLazyRouteImport.update({
  id: '/collections/all',
  path: '/collections/all',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/collections/all.lazy').then((d) => d.Route),
)
const AccountUpdatePasswordLazyRoute =
  AccountUpdatePasswordLazyRouteImport.update({
    id: '/account/update-password',
    path: '/account/update-password',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/account/update-password.lazy').then((d) => d.Route),
  )
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSoldoutRoute = CollectionsSoldoutRouteImport.update({
  id: '/collections/soldout',
  path: '/collections/soldout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsOldRoute = CollectionsOldRouteImport.update({
  id: '/collections/old',
  path: '/collections/old',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNewRoute = CollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsAccessoriesRoute = CollectionsAccessoriesRouteImport.update({
  id: '/collections/accessories',
  path: '/collections/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUpdateInformationRoute =
  AccountUpdateInformationRouteImport.update({
    id: '/account/update-information',
    path: '/account/update-information',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/update-information': typeof AccountUpdateInformationRoute
  '/collections/accessories': typeof CollectionsAccessoriesRoute
  '/collections/new': typeof CollectionsNewRoute
  '/collections/old': typeof CollectionsOldRoute
  '/collections/soldout': typeof CollectionsSoldoutRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/update-password': typeof AccountUpdatePasswordLazyRoute
  '/collections/all': typeof CollectionsAllLazyRoute
  '/info/FAQ': typeof InfoFAQLazyRoute
  '/info/about': typeof InfoAboutLazyRoute
  '/payment/successful': typeof PaymentSuccessfulLazyRoute
  '/policy/privacy-policy': typeof PolicyPrivacyPolicyLazyRoute
  '/policy/refund-policy': typeof PolicyRefundPolicyLazyRoute
  '/policy/shipping-policy': typeof PolicyShippingPolicyLazyRoute
  '/policy/terms-conditions': typeof PolicyTermsConditionsLazyRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/update-information': typeof AccountUpdateInformationRoute
  '/collections/accessories': typeof CollectionsAccessoriesRoute
  '/collections/new': typeof CollectionsNewRoute
  '/collections/old': typeof CollectionsOldRoute
  '/collections/soldout': typeof CollectionsSoldoutRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/update-password': typeof AccountUpdatePasswordLazyRoute
  '/collections/all': typeof CollectionsAllLazyRoute
  '/info/FAQ': typeof InfoFAQLazyRoute
  '/info/about': typeof InfoAboutLazyRoute
  '/payment/successful': typeof PaymentSuccessfulLazyRoute
  '/policy/privacy-policy': typeof PolicyPrivacyPolicyLazyRoute
  '/policy/refund-policy': typeof PolicyRefundPolicyLazyRoute
  '/policy/shipping-policy': typeof PolicyShippingPolicyLazyRoute
  '/policy/terms-conditions': typeof PolicyTermsConditionsLazyRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/update-information': typeof AccountUpdateInformationRoute
  '/collections/accessories': typeof CollectionsAccessoriesRoute
  '/collections/new': typeof CollectionsNewRoute
  '/collections/old': typeof CollectionsOldRoute
  '/collections/soldout': typeof CollectionsSoldoutRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/account/update-password': typeof AccountUpdatePasswordLazyRoute
  '/collections/all': typeof CollectionsAllLazyRoute
  '/info/FAQ': typeof InfoFAQLazyRoute
  '/info/about': typeof InfoAboutLazyRoute
  '/payment/successful': typeof PaymentSuccessfulLazyRoute
  '/policy/privacy-policy': typeof PolicyPrivacyPolicyLazyRoute
  '/policy/refund-policy': typeof PolicyRefundPolicyLazyRoute
  '/policy/shipping-policy': typeof PolicyShippingPolicyLazyRoute
  '/policy/terms-conditions': typeof PolicyTermsConditionsLazyRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/register'
    | '/account/update-information'
    | '/collections/accessories'
    | '/collections/new'
    | '/collections/old'
    | '/collections/soldout'
    | '/products/$productId'
    | '/account/update-password'
    | '/collections/all'
    | '/info/FAQ'
    | '/info/about'
    | '/payment/successful'
    | '/policy/privacy-policy'
    | '/policy/refund-policy'
    | '/policy/shipping-policy'
    | '/policy/terms-conditions'
    | '/account'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/register'
    | '/account/update-information'
    | '/collections/accessories'
    | '/collections/new'
    | '/collections/old'
    | '/collections/soldout'
    | '/products/$productId'
    | '/account/update-password'
    | '/collections/all'
    | '/info/FAQ'
    | '/info/about'
    | '/payment/successful'
    | '/policy/privacy-policy'
    | '/policy/refund-policy'
    | '/policy/shipping-policy'
    | '/policy/terms-conditions'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/account/register'
    | '/account/update-information'
    | '/collections/accessories'
    | '/collections/new'
    | '/collections/old'
    | '/collections/soldout'
    | '/products/$productId'
    | '/account/update-password'
    | '/collections/all'
    | '/info/FAQ'
    | '/info/about'
    | '/payment/successful'
    | '/policy/privacy-policy'
    | '/policy/refund-policy'
    | '/policy/shipping-policy'
    | '/policy/terms-conditions'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountUpdateInformationRoute: typeof AccountUpdateInformationRoute
  CollectionsAccessoriesRoute: typeof CollectionsAccessoriesRoute
  CollectionsNewRoute: typeof CollectionsNewRoute
  CollectionsOldRoute: typeof CollectionsOldRoute
  CollectionsSoldoutRoute: typeof CollectionsSoldoutRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  AccountUpdatePasswordLazyRoute: typeof AccountUpdatePasswordLazyRoute
  CollectionsAllLazyRoute: typeof CollectionsAllLazyRoute
  InfoFAQLazyRoute: typeof InfoFAQLazyRoute
  InfoAboutLazyRoute: typeof InfoAboutLazyRoute
  PaymentSuccessfulLazyRoute: typeof PaymentSuccessfulLazyRoute
  PolicyPrivacyPolicyLazyRoute: typeof PolicyPrivacyPolicyLazyRoute
  PolicyRefundPolicyLazyRoute: typeof PolicyRefundPolicyLazyRoute
  PolicyShippingPolicyLazyRoute: typeof PolicyShippingPolicyLazyRoute
  PolicyTermsConditionsLazyRoute: typeof PolicyTermsConditionsLazyRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/terms-conditions': {
      id: '/policy/terms-conditions'
      path: '/policy/terms-conditions'
      fullPath: '/policy/terms-conditions'
      preLoaderRoute: typeof PolicyTermsConditionsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/shipping-policy': {
      id: '/policy/shipping-policy'
      path: '/policy/shipping-policy'
      fullPath: '/policy/shipping-policy'
      preLoaderRoute: typeof PolicyShippingPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/refund-policy': {
      id: '/policy/refund-policy'
      path: '/policy/refund-policy'
      fullPath: '/policy/refund-policy'
      preLoaderRoute: typeof PolicyRefundPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/privacy-policy': {
      id: '/policy/privacy-policy'
      path: '/policy/privacy-policy'
      fullPath: '/policy/privacy-policy'
      preLoaderRoute: typeof PolicyPrivacyPolicyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/successful': {
      id: '/payment/successful'
      path: '/payment/successful'
      fullPath: '/payment/successful'
      preLoaderRoute: typeof PaymentSuccessfulLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/about': {
      id: '/info/about'
      path: '/info/about'
      fullPath: '/info/about'
      preLoaderRoute: typeof InfoAboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/FAQ': {
      id: '/info/FAQ'
      path: '/info/FAQ'
      fullPath: '/info/FAQ'
      preLoaderRoute: typeof InfoFAQLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/all': {
      id: '/collections/all'
      path: '/collections/all'
      fullPath: '/collections/all'
      preLoaderRoute: typeof CollectionsAllLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/update-password': {
      id: '/account/update-password'
      path: '/account/update-password'
      fullPath: '/account/update-password'
      preLoaderRoute: typeof AccountUpdatePasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/soldout': {
      id: '/collections/soldout'
      path: '/collections/soldout'
      fullPath: '/collections/soldout'
      preLoaderRoute: typeof CollectionsSoldoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/old': {
      id: '/collections/old'
      path: '/collections/old'
      fullPath: '/collections/old'
      preLoaderRoute: typeof CollectionsOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/new': {
      id: '/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof CollectionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/accessories': {
      id: '/collections/accessories'
      path: '/collections/accessories'
      fullPath: '/collections/accessories'
      preLoaderRoute: typeof CollectionsAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/update-information': {
      id: '/account/update-information'
      path: '/account/update-information'
      fullPath: '/account/update-information'
      preLoaderRoute: typeof AccountUpdateInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountUpdateInformationRoute: AccountUpdateInformationRoute,
  CollectionsAccessoriesRoute: CollectionsAccessoriesRoute,
  CollectionsNewRoute: CollectionsNewRoute,
  CollectionsOldRoute: CollectionsOldRoute,
  CollectionsSoldoutRoute: CollectionsSoldoutRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  AccountUpdatePasswordLazyRoute: AccountUpdatePasswordLazyRoute,
  CollectionsAllLazyRoute: CollectionsAllLazyRoute,
  InfoFAQLazyRoute: InfoFAQLazyRoute,
  InfoAboutLazyRoute: InfoAboutLazyRoute,
  PaymentSuccessfulLazyRoute: PaymentSuccessfulLazyRoute,
  PolicyPrivacyPolicyLazyRoute: PolicyPrivacyPolicyLazyRoute,
  PolicyRefundPolicyLazyRoute: PolicyRefundPolicyLazyRoute,
  PolicyShippingPolicyLazyRoute: PolicyShippingPolicyLazyRoute,
  PolicyTermsConditionsLazyRoute: PolicyTermsConditionsLazyRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
